name = "SpannerComparison"
uuid = "12345678-1234-1234-1234-1234567890ab"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DataStructures = "0.19.3"
Dates = "1.11.0"
Distances = "0.10.12"
FileIO = "1.17.1"
Graphs = "1.13.3"
JLD2 = "0.6.3"
LinearAlgebra = "1.12.0"
Plots = "1.41.3"
Printf = "1.11.0"
Random = "1.11.0"
Reexport = "1.2.2"
SimpleWeightedGraphs = "1.5.1"
StaticArrays = "1.9.16"
Statistics = "1.11.1"
